version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=5000
      - APP_ENV=development
    depends_on:
      - postgres
    networks:
      - fleet-network
    volumes:
      - ./templates:/app/templates:ro  # Mount templates for hot reload in dev
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=fleetuser
      - POSTGRES_PASSWORD=fleetpass
      - POSTGRES_DB=fleetdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fleet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleetuser -d fleetdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@fleet.local
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - fleet-network
    profiles:
      - tools

volumes:
  postgres_data:

networks:
  fleet-network:
    driver: bridge