[build]
buildCommand = "go mod download && go build -ldflags='-s -w' -o main ."

[deploy]
startCommand = "./main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Enable Railway's build caching
[build.cache]
enabled = true
