[build]
buildCommand = "go mod download && go build -ldflags='-s -w' -o hs-bus ."

[deploy]
startCommand = "./hs-bus"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Enable Railway's build caching
[build.cache]
enabled = true
