[build]
builder = "nixpacks"
buildCommand = """
mv import_mileage.go import_mileage.go.bak 2>/dev/null || true && \
sed -i '2i import "fmt"' handlers.go && \
sed -i '/func importMileageHandler/,/^}$/d' handlers.go && \
sed -i '/func doMileageImport/,/^}$/d' handlers.go && \
sed -i '/func insertMileageRecord/,/^}$/d' handlers.go && \
sed -i '/type MileageRecord/,/^}$/d' handlers.go && \
sed -i 's|.*"/import-mileage".*||g' main.go && \
go mod tidy && \
go build -o main .
"""

[deploy]
startCommand = "./main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
